apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase-backend
  template:
    metadata:
      labels:
        app: showcase-backend
    spec:
      containers:
        - name: showcase-backend
          image: raccoonsteam/backend:events
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_URL
              value: "showcase-redis-service.default:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kyma-showcase-secret
                  key: REDIS_PASSWORD
            - name: PORT
              value: "8081"
            - name: EVENT_URL
              value: "http://eventing-event-publisher-proxy.kyma-system/publish"
